%YAML:1.0

# Estimator
use_vimo:  1                        # set to 1 to run VIMO, set to 0 to run VINS-Mono
process_at_control_input_rate: 1    # set to 1 if control commands for VIMO have higher frequency than IMU

# topic names
imu_topic: "/blackbird/imu"
image_topic: "/camera/image_raw"
control_topic: "/blackbird/rotor_rpm"

# paths to store results of the state, computation times and external force estimates
output_path: "/home/barza/barza-vins-out" # path for csv file

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 1024
image_height: 768
distortion_parameters:
   k1: 0  
   k2: 0 
   p1: 0
   p2: 0
projection_parameters:
   fx: 665.107510106
   fy: 665.107510106
   cx: 511.5
   cy: 383.5

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.0, 0.0, 1.0, -1.0, 0.0, 0.0, 0.0, -1.0, 0.0] #[0.9999, 0.0119, 0.0026, 0.0025, 0.0014, -1.0000, -0.0119, 0.9999, 0.0014] #[ 1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 1.0, 0.0]

#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.0, 0.0, 0.0]

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 0             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.06     # max solver itration time (ms), to guarantee real time
max_num_iterations: 10    # max solver itrations, to guarantee real time
keyframe_parallax: 10.0   # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: !!opencv-matrix # accelerometer measurement noise standard deviation.
   rows: 3
   cols: 1
   dt: d
   data: [0.3, 0.3, 0.3]

gyr_n: 0.1         # gyroscope measurement noise standard deviation.     
acc_w: 0.001       # accelerometer bias random work noise standard deviation. 
gyr_w: 0.003       # gyroscope bias random work noise standard deviation.
g_norm: 9.81007    # gravity magnitude

#model parameters: The more accurate parameters you provide, the better performance
control_thrust_z_n: 0.01      # mass normalized collective thrust in body z axis noise standard deviation
control_thrust_x_y_n: 0.005   # mass normalized collective thrust in body x and y axis noise standard deviation
fext_norm_weight: 0.001       # weight for external force norm 
scale_thrust_input: 1 

#loop closure parameters
loop_closure: 0                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0             # useful in real-time and large project
pose_graph_save_path: "/home/barza/barza-vins-out/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet).

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ